#import "template.typ": *
#let results_limit = toml("results/log_concave_extension/high-resolution/summary.toml")
#let results_fd = toml("results/finite_dim/finite-dim/summary.toml")

= Pointwise bounds on the eigenfunction <sec:pointwise>

The method of particular solutions of @numerics returns an approximate eigenpair $(lambda_*, phi.alt_*)$ that satisfies the interior equation $-∆ phi.alt_* = lambda_* phi.alt_*$ exactly and has a small residual in the boundary condition. In this section we turn this boundary residual into a pointwise bound on the distance to the true principal eigenfunction $phi.alt_1$.

We give two derivations from this residual to a pointwise bound. In @sec:pointwise-limit we treat the limit $d = oo$, where the problem reduces to the operator $L = -∆ + nabla V dot nabla$ on $Q$ and the ultracontractivity estimates of @sec:ultracontractivity make the bound fully explicit. In the finite-dimensional case, we instead follow @moler_bounds_1968 and add a harmonic correction that restores the boundary condition exactly, then control the correction by a barrier.

== Pointwise bounds in the limit $d = oo$ <sec:pointwise-limit>

At $d = oo$ the barrel eigenvalue problem reduces to the operator $L = -∆ + nabla V dot nabla$ on the base $Q$, self-adjoint on $L^2(mu)$ with $dif mu = Z^(-1) e^(-V) dif x$. We use its Neumann eigenpairs $0 = lambda_0 < lambda_1 ≤ lambda_2 ≤ ...$, with $L^2(mu)$-orthonormal eigenfunctions $phi.alt_0 ≡ 1, phi.alt_1, phi.alt_2, ...$. We do not normalize the approximation $phi.alt_*$. Instead, we compare it to the corresponding multiple of $phi.alt_1$ and compute the residual $(L - lambda_*) phi.alt_*$.

Let $(P_t)_(t ≥ 0)$ be the semigroup generated by $-L$, so that $∂_t P_t = -L P_t$ and $P_t phi.alt_k = e^(-lambda_k t) phi.alt_k$. Set $Q_t := e^(lambda_1 t) P_t$, so that the principal eigenfunction is a fixed point, $Q_t phi.alt_1 = phi.alt_1$, while $Q_t phi.alt_* -> inner(phi.alt_1, phi.alt_*) phi.alt_1$ as $t -> oo$. The ultracontractivity estimate of @thm:ultracontractivity gives a constant $C_t$ -- computed at $d = oo$ in @sec:ultracontractivity -- with
$
norm(P_t f)_oo ≤ C_t norm(f)_(L^2(mu)), "for all" t > 0.
$

#theorem[
  Let $phi.alt_1$ be the principal eigenfunction of $L = -∆ + nabla V dot nabla$ on $Q$, supposed $phi.alt_1$, is normalized such that $norm(phi.alt_1)_(L^2(mu)) = 1$. Let $phi.alt_*$ be the approximation produced by the method of particular solutions with approximate eigenvalue $lambda_*$. Let $a = inner(phi.alt_*, phi.alt_1)$, then
  $
  norm(phi.alt_* - a phi.alt_1)_oo
  ≤& (norm((L - lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo) ((e^(s_1 lambda_1) - 1) / lambda_1
  + integral_(s_1)^oo C_(s / 2) e^(-(lambda_2 / 2 - lambda_1) s) dif s) ,
  $
  for any $s_1 > 0$.
]<thm:pointwise-limit>
#proof[
  Because $Q_t phi.alt_1 = phi.alt_1$ and $Q_t phi.alt_* -> a phi.alt_1$ as $t -> oo$, where $a = inner(phi.alt_*, phi.alt_1)$, and since $∂_s Q_s = -(L - lambda_1) Q_s$, we write the error as a time integral,
  $
  a phi.alt_1 - phi.alt_* = lim_(t -> oo) (Q_t phi.alt_* - phi.alt_*) = - integral_0^oo Q_s (L - lambda_1) phi.alt_* dif s,
  $

  and therefore

  $
  norm(phi.alt_* - a phi.alt_1)_oo ≤ integral_0^oo norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s.
  $<eq:my-favorite-integral>

  The function $(L - lambda_1) phi.alt_*$ is $L^2(mu)$-orthogonal to both $phi.alt_0 ≡ 1$ and $phi.alt_1$. Indeed, orthogonality to $phi.alt_0$ follows immediately from $(L - lambda_1) phi.alt_* = (L - lambda_*) phi.alt_* + (lambda_* - lambda_1) phi.alt_*$ and the fact that $phi.alt_*$ is antisymmetric in $x_1$ while $mu$ is symmetric. Orthogonality to the principal eigenfunction is by self-adjointness, $inner(phi.alt_1, (L - lambda_1) phi.alt_*) = inner((L - lambda_1) phi.alt_1, phi.alt_*) = 0$. Hence $P_s$ lets $(L - lambda_1) phi.alt_*$ decay at the rate $e^(-lambda_2)$ instead of only $e^(-lambda_1)$, and therefore,

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  = e^(lambda_1 s) norm(P_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  ≤ e^(-(lambda_2 - lambda_1) s) norm((L - lambda_1) phi.alt_*)_(L^2(mu)).
  $

  If we leave ourselves some slack and apply $Q_s$ only for time $s slash 2$, then

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  ≤ e^(-(lambda_2 - lambda_1) s slash 2) norm(Q_(s slash 2)(L - lambda_1) phi.alt_*)_(L^2(mu)),
  $

  and we can use the remaining smoothing time $s slash 2$ to pass to $L^oo$. Applying the ultracontractivity estimate of @thm:ultracontractivity,

  $
  norm(Q_(s) (L - lambda_1) phi.alt_*)_oo
  ≤ C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) norm((L - lambda_1) phi.alt_*)_(L^2(mu)).
  $<eq:splitting-trick>

  Since $C_(s slash 2)$ blows up as $s -> 0$, this bound is only useful for times above some threshold $s_1$, which is a free parameter. Below it we resort to the maximum-principle estimate $norm(P_t g)_oo ≤ norm(g)_oo$, that is 

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_oo
  ≤ e^(lambda_1 s) norm((L - lambda_1) phi.alt_*)_oo.
  $

  We now split the integral in @eq:my-favorite-integral at $s_1$ and write $(L - lambda_1) phi.alt_* = (L - lambda_*) phi.alt_* + (lambda_* - lambda_1) phi.alt_*$. The short-time contribution satisfies

  $
  integral_0^(s_1) norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s ≤ (norm((L - lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo) integral_0^(s_1) e^(lambda_1 s) dif s,
  $

  For the long-time contribution, since $mu$ is a probability measure,
  $
  norm((L - lambda_1) phi.alt_*)_(L^2(mu))
  &≤ norm((L - lambda_*) phi.alt_*)_(L^2(mu)) + abs(lambda_* - lambda_1) norm(phi.alt_*)_(L^2(mu)) \
  &≤ norm((L - lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo.
  $
  Therefore,
  $
  integral_(s_1)^oo norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s
  ≤& (norm((L - lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo) \
  &times integral_(s_1)^oo C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) dif s.
  $

  Adding the two contributions and evaluating $integral_0^(s_1) e^(lambda_1 s) dif s = (e^(s_1 lambda_1) - 1) slash lambda_1$ gives the stated bound.
]

The above theorem gives a pointwise bound on the _initial condition_ of @eq:limit-ivp. Since we expect to observe the hot spot at $t=1 slash 8$ (or $r=0$), we have to propagate the error in time. 

#theorem[
  $
  norm(h_* (t) - a h_1 (t)) ≤ e^(lambda_* t) E + abs(e^(lambda_* t - lambda_1 t)) (norm(phi.alt_*)_oo + E)
  $
]
#proof[
  We have $h_* = e^(lambda_*) P_t^(Delta_N) phi.alt_*$ and $h_* = e^(lambda_1) P_t^(Delta_N) phi.alt_*$ where $P_t^(Delta_N) = e^(Delta_N t)$ for the Neumann Laplacian on $Delta_N$ on $Q$. Indeed, we have $∂_t h = Delta_N h + lambda_h$ then setting $u = e^(-lambda t) h(x,t)$ gives $partial_t u = Delta_N u$. Hence $u = P_t^(Delta_N) phi.alt$ implies $h(t) = e^(lambda_t) P_t^(Delta_N) phi.alt$.

  Now we use the fact that $P^(Delta_N)_t$ is an $L_oo$ contraction to conclude

  $
  norm(h_* (t) - a h_1 (t))_oo ≤ e^(lambda_* t) norm(phi.alt_* - a phi.alt_1)_oo + abs(e^(lambda_* t - lambda_1 t)) (norm(phi.alt_*)_oo + norm(phi.alt_* - a phi.alt_1)_oo.)
  $
  
]

#remark[
  We chose to rescale the true eigenfunction instead of normalizing the
  approximate eigenfunction in the theorem above. To see why this is
  sufficient to validate the hotspot property, define $H(phi.alt_*) = sup_(Omega^circle) phi.alt_* - sup_(∂Omega) phi.alt_*$. If $norm(phi.alt_* - a phi.alt_1)_oo ≤ E(phi.alt_*)$, then

  $
  H(a phi.alt_1) ≥ H(phi.alt_*) - 2 E(phi.alt_*).
  $

  Choose the sign of $phi.alt_1$ so that $a > 0$. Since
  $H(a phi.alt_1) = a H(phi.alt_1)$, it follows that $phi.alt_1$
  achieves a strict global maximum in the interior whenever
  $
  H(phi.alt_*) > 2 E(phi.alt_*).
  $

  This saves us from relying on an enclosure of the $L^2$ norm of the
  approximate eigenfunction.
]

#remark[
  The even time split $s = s slash 2 + s slash 2$ leading to @eq:splitting-trick is arbitrary. Splitting instead as $s = alpha s + (1 - alpha) s$, with smoothing time $alpha s$ and decay time $(1 - alpha) s$, replaces the integrand factor by
  $
  C_(alpha s) e^(lambda_1 alpha s - (lambda_2 - lambda_1) (1 - alpha) s),
  $
  which can be optimized over $alpha in (0, 1)$.
]

#remark[
  Since the ultracontractivity constant is decreasing in time, we have

  $
  integral_(s_1)^oo C_(alpha s) e^(lambda_1 alpha s - (lambda_2 - lambda_1) (1 - alpha) s) dif s 
  &<= sum C_(alpha s_i) integral_(s_i)^(s_(i+1)) e^(lambda_1 alpha s - (lambda_2 - lambda_1) (1 - alpha) s) dif s \
  &= sum C_(alpha s_i) (e^((lambda_1 - lambda_2(1 - alpha))s_(i+1)) - e^((lambda_1 - lambda_2(1 - alpha))s_i)) / (lambda_1 - lambda_2(1 - alpha))
  $
]

=== Numerical inputs in the limit $d = oo$ <sec:pointwise-limit-numerics>

For the log-concave limit, the optimized splitting uses $s_1 = num(#results_limit.pointwise_limit.s1)$ and $alpha = num(#results_limit.pointwise_limit.alpha)$. The quantities entering @thm:pointwise-limit are collected in @tab:pointwise-limit-inputs.

#figure(
  table(
    columns: (1.65fr, 1fr),
    align: (left, left),
    [*Quantity*], [*Computed value*],
    [$d$], [$= oo$],
    [$norm((L - lambda_*) phi.alt_*)_oo$], [$lt.tilde #num(results_limit.pointwise_limit.residual_bound)$],
    [$norm(phi.alt_*)_oo$], [$lt.tilde #num(results_limit.pointwise_limit.phi_linf_bound)$],
    [$sup_(Omega^circle) phi.alt_* - sup_(partial Omega) phi.alt_*$], [$approx #num(results_limit.mps_candidate.hot_spot_effect)$],
    [$lambda_1$], [$in #interval(results_limit.eigenvalue_bounds.lambda1_lower, results_limit.eigenvalue_bounds.lambda1_upper)$],
    [$lambda_*$], [$= #num(results_limit.mps_candidate.lambda)$],
    [$lambda_2$], [$>= #num(results_limit.eigenvalue_bounds.lambda2_lower)$],
    [$s_1$], [$= #num(results_limit.pointwise_limit.s1)$],
    [$alpha$], [$= #num(results_limit.pointwise_limit.alpha)$],
    [$(e^(s_1 lambda_1) - 1) slash lambda_1$], [$lt.tilde #num(results_limit.pointwise_limit.head_term)$],
    [$integral_(s_1)^oo C_(alpha s) e^((lambda_1 - lambda_2(1 - alpha))s) dif s$], [$lt.tilde #num(results_limit.pointwise_limit.tail_term)$],
    [$norm(phi.alt_* - a phi.alt_1)_oo$], [$lt.tilde #num(results_limit.pointwise_limit.pointwise_linf_bound)$],
  ),
  caption: [Quantities entering the pointwise estimate in the log-concave limit. The reported values have not been enclosed with interval arithmetic.],
  kind: table,
) <tab:pointwise-limit-inputs>

#let limit_amplification = (
  results_limit.pointwise_limit.head_term
  + results_limit.pointwise_limit.tail_term
)
#let limit_eigenvalue_term = (
  results_limit.pointwise_limit.lambda_error
  * results_limit.pointwise_limit.phi_linf_bound
)

Keeping the residual and eigenvalue-error contributions visible, substitution into @thm:pointwise-limit gives

$
norm(phi.alt_* - a phi.alt_1)_oo
&lt.tilde (
  #num(results_limit.pointwise_limit.residual_bound)
  + #num(results_limit.pointwise_limit.lambda_error)
    dot #num(results_limit.pointwise_limit.phi_linf_bound)
) \
&quad times (
  #num(results_limit.pointwise_limit.head_term)
  + #num(results_limit.pointwise_limit.tail_term)
) \
&lt.tilde #num(results_limit.pointwise_limit.pointwise_linf_bound).
$ <eq:pointwise-limit-numerical>

== Pointwise bounds in the finite-dimensional case

In the limit $d = oo$ the eigenvalue problem is effectively an interior one: the mass of the barrel concentrates at the outer boundary, the approximation $phi.alt_*$ satisfies the Neumann condition on $∂Q$ by construction, and the only error left to control is the "interior" residual $(L - lambda_*) phi.alt_*$. In finite dimensions this is no longer the case. The approximation satisfies the interior equation $-∆ phi.alt_* = lambda_* phi.alt_*$ exactly, but it now leaves a residual in the Neumann condition on $Gamma_1 union Gamma_2$. Following @moler_bounds_1968, we first internalize this boundary residual, then the same proof as in @sec:pointwise-limit applies.

We work on the half-barrel

$
F_d^+ := {(x,z) in F_d (Q,V) : x_1 ≥ 0}
$

and split its boundary into

$
Gamma_0 &= {(x,z) in ∂F_d^+ : x_1 = 0}, \
Gamma_1 &= {(x,z) in ∂F_d^+ : x_1 = 2 pi "or" abs(x_2) = 1}, \
Gamma_2 &= {(x,z) in ∂F_d^+ : abs(z) = sqrt(d)/2 (1 - V(x)/d)}.
$

Here $Gamma_0$ is the symmetry plane, on which $phi.alt_*$ and $phi.alt_1$ vanish because they are odd in $x_1$, $Gamma_1$ denotes the flat Neumann walls on which the boundary condition is satisfied by designm and $Gamma_2$ is the curved barrel wall, on which the Neumann condition is only satisfied approximately. All Laplacians, gradients, and normal derivatives in the remainder of this subsection are the ordinary Euclidean ones on $F_d^+$.

We correct the boundary condition with a harmonic function $w$ solving

$
-∆ w &= 0 "in" F_d^+, \
w &= 0 "on" Gamma_0, \
∂_arrow(n) w(x, z) &= -∂_arrow(n) phi.alt_*(x, z) "on" Gamma_1 union Gamma_2.
$<eq:harmonic-correction>

By construction $phi.alt_* + w$ satisfies the mixed boundary conditions exactly on $F_d^+$. Extend $w$ oddly across $Gamma_0$. Since $w$ is harmonic, using $-∆ phi.alt_* = lambda_* phi.alt_*$ and $-∆ w = 0$, we have

$
(-∆ - lambda_1)(phi.alt_* + w) = (lambda_* - lambda_1) phi.alt_* - lambda_1 w.
$<eq:internalized-residual>

The corrected function $phi.alt_* + w$ thus takes over the role that $phi.alt_*$ played in the limit case. It remains to control the correction $w$, which we do with a barrier.

#lemma[
  Let $w$ solve @eq:harmonic-correction, and let $v$ be a supersolution satisfying
  $
  -∆ v &≥ 0 "in" F_d^+, \
  v &= 0 "on" Gamma_0, \
  ∂_arrow(n) v &≥ 0 "on" Gamma_1, \
  ∂_arrow(n) v(x, z) &≥ abs(∂_arrow(n) phi.alt_*(x, z)) "on" Gamma_2.
  $
  Then $abs(w) ≤ v$ on $F_d^+$, in particular $norm(w)_oo ≤ norm(v)_oo$.
]<lem:barrier>
#proof[
  Set $f := w - v$. Then $-∆ f ≤ 0$ in $F_d^+$, with $∂_arrow(n) f ≤ 0$ on $Gamma_1 union Gamma_2$ and $f = 0$ on $Gamma_0$. Testing against the positive part $f^+$ and integrating by parts,
  $
  norm(nabla f^+)_2^2 = integral_(F_d^+) nabla f dot nabla f^+ = integral_(F_d^+) (-∆ f) f^+ + integral_(Gamma_1 union Gamma_2) (∂_arrow(n) f) f^+ ≤ 0,
  $
  so $f^+$ is constant. Since it vanishes on $Gamma_0$ it is identically zero, giving $w ≤ v$. Repeating the argument with $-w$ in place of $w$ yields $abs(w) ≤ v$.
]

#theorem[
  Let $phi.alt_1$ be the principal Neumann eigenfunction of $-∆$ on $Omega_d$, normalized such that $norm(phi.alt_1)_2 = 1$, and let $phi.alt_*$, satisfying $-∆ phi.alt_* = lambda_* phi.alt_*$ exactly in the interior, be the approximation produced by the method of particular solutions. Let $w$ be the harmonic correction @eq:harmonic-correction and $v$ a barrier as in @lem:barrier. Let $a = inner(phi.alt_* + w, phi.alt_1)$. Then
  $
  norm(phi.alt_* - a phi.alt_1)_oo
  ≤& norm(v)_oo \
  &+ (abs(lambda_* - lambda_1) norm(phi.alt_*)_oo + lambda_1 norm(v)_oo) ((e^(s_1 lambda_1) - 1) / lambda_1 + integral_(s_1)^oo C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) dif s),
  $
  for any $s_1 > 0$.
]<thm:pointwise-finite>
#proof[
  Because $phi.alt_* + w$ satisfies the Neumann condition exactly, the argument of @thm:pointwise-limit applies to $phi.alt_* + w$ in place of $phi.alt_*$ and $-∆$ in place of $L$. The approximate eigenfunction $phi.alt_*$ is odd in $x_1$ by design and $w$ is odd by @eq:harmonic-correction, so $phi.alt_* + w$ is orthogonal to $phi.alt_0 ≡ 1$. Moreover, the exact Neumann condition makes the boundary terms in Green's identity vanish, and hence
  $
  inner(phi.alt_1, (-∆ - lambda_1)(phi.alt_* + w))
  = inner((-∆ - lambda_1) phi.alt_1, phi.alt_* + w) = 0.
  $
  Thus, if $P_s$ denotes the Neumann heat semigroup on $Omega_d$ and $Q_s = e^(lambda_1 s) P_s$, then $Q_s (phi.alt_* + w) -> a phi.alt_1$ as $s -> oo$. The same time split of @eq:my-favorite-integral at $s_1$, the maximum principle below $s_1$, and the $s slash 2$ ultracontractivity bound above $s_1$, gives

  $
  norm(phi.alt_* + w - a phi.alt_1)_oo ≤& norm((-∆ - lambda_1)(phi.alt_* + w))_oo integral_0^(s_1) e^(lambda_1 s) dif s \
  &+ norm((-∆ - lambda_1)(phi.alt_* + w))_2 integral_(s_1)^oo C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) dif s.
  $

  From @eq:internalized-residual and the barrier bound it follows pointwise that

  $
  norm((-∆ - lambda_1)(phi.alt_* + w))_oo
  ≤ abs(lambda_* - lambda_1) norm(phi.alt_*)_oo + lambda_1 norm(v)_oo.
  $
  Since the $L^2$ norm is taken with respect to the normalized invariant measure on $Omega_d$, the same expression also bounds the $L^2$ norm,
  $
  norm((-∆ - lambda_1)(phi.alt_* + w))_2
  ≤ norm((-∆ - lambda_1)(phi.alt_* + w))_oo
  ≤ abs(lambda_* - lambda_1) norm(phi.alt_*)_oo + lambda_1 norm(v)_oo.
  $

  Inserting these bounds, evaluating $integral_0^(s_1) e^(lambda_1 s) dif s = (e^(s_1 lambda_1) - 1) slash lambda_1$, and using the triangle inequality
  $
  norm(phi.alt_* - a phi.alt_1)_oo
  ≤ norm(phi.alt_* + w - a phi.alt_1)_oo + norm(w)_oo,
  $
  gives the stated bound.
]

=== Numerical inputs at $d = 10^18$ <sec:pointwise-finite-numerics>

We now record the computed quantities entering @thm:pointwise-finite. As in the optimized time splitting following @thm:pointwise-limit, write $s = alpha s + (1 - alpha) s$. The long-time contribution is then bounded by
$
integral_(s_1)^oo C_(alpha s)
e^((lambda_1 - lambda_2(1 - alpha))s) dif s.
$
For the finite-dimensional computation we take $s_1 = num(#results_fd.pointwise.s1)$ and $alpha = num(#results_fd.pointwise.alpha)$. The remaining inputs are collected in @tab:pointwise-finite-inputs.

#figure(
  table(
    columns: (1.65fr, 1fr),
    align: (left, left),
    [*Quantity*], [*Computed value*],
    [$d$], [$= #num(results_fd.mps_candidate.dimension)$],
    [$norm(partial_arrow(n) phi.alt_*)_oo$], [$lt.tilde #num(results_fd.residual.normal_derivative_inf)$],
    [$norm(phi.alt_*)_oo$], [$lt.tilde #num(results_fd.eigenfunction.sampled_linf)$],
    [$sup_(Omega_d^circle) phi.alt_* - sup_(partial Omega_d) phi.alt_*$], [$approx #num(results_fd.eigenfunction.hot_spot_effect)$],
    [$lambda_1$], [$in #interval(results_fd.eigenvalue_bounds.lambda1_lower, results_fd.eigenvalue_bounds.lambda1_upper)$],
    [$lambda_*$], [$= #num(results_fd.mps_candidate.lambda)$],
    [$lambda_2$], [$>= #num(results_fd.eigenvalue_bounds.lambda2_lower)$],
    [$s_1$], [$= #num(results_fd.pointwise.s1)$],
    [$alpha$], [$= #num(results_fd.pointwise.alpha)$],
    [$(e^(s_1 lambda_1) - 1) slash lambda_1$], [$lt.tilde #num(results_fd.pointwise.head_term)$],
    [$integral_(s_1)^oo C_(alpha s) e^((lambda_1 - lambda_2(1 - alpha))s) dif s$], [$lt.tilde #num(results_fd.pointwise.tail_term)$],
    [$norm(v)_oo$], [unknown],
  ),
  caption: [Quantities entering the finite-dimensional pointwise estimate. The residual, eigenfunction norm, and hot-spot effect are obtained from floating-point sampling and have not been enclosed with interval arithmetic.],
  kind: table,
) <tab:pointwise-finite-inputs>

#let fd_amplification = results_fd.pointwise.head_term + results_fd.pointwise.tail_term
#let fd_eigenvalue_term = (
  results_fd.eigenvalue_bounds.lambda_error
  * results_fd.eigenfunction.sampled_linf
)
#let fd_constant_error = fd_eigenvalue_term * fd_amplification
#let fd_barrier_coefficient = (
  1
  + results_fd.eigenvalue_bounds.lambda1_upper * fd_amplification
)

Substituting the available values into @thm:pointwise-finite gives the provisional estimate
$
norm(phi.alt_* - a phi.alt_1)_oo
lt.tilde #num(fd_constant_error)
+ #num(fd_barrier_coefficient) norm(v)_oo.
$ <eq:pointwise-finite-numerical>
This cannot yet be evaluated because $norm(v)_oo$ is unknown. Moreover, even if the barrier term vanished, the present eigenvalue enclosure would produce an error much larger than the hot-spot effect. Thus the finite element enclosure is sufficient to locate the candidate in the spectrum, but a sharper residual-based enclosure of $lambda_1$ is also needed for a certificate.



// #inline-note-a[
//   Maybe the Rayleigh-quotient should be computed like this:
//   $
//   lambda_1 ≤ integral abs(nabla phi.alt_*)^2
//   &= -integral phi.alt_* ∆ phi.alt_* + integral phi.alt_* ∂_arrow(n) phi.alt_* \
//   &= lambda_* + integral_Gamma_1 phi.alt_* ∂_arrow(n) phi.alt_*
//   $
// ]
