#import "template.typ": *

= Pointwise bounds of the eigenfunction <sec:pointwise>

The method of particular solutions of @numerics returns an approximate eigenpair $(lambda_*, phi.alt_*)$ that satisfies the interior equation $-∆ phi.alt_* = lambda_* phi.alt_*$ exactly and has a small residual in the boundary condition. In this section we turn this boundary residual into a pointwise bound on the distance to the true principal eigenfunction $phi.alt_1$. We split the boundary of the reduced barrel $Omega_d = {(x, r) in Q times RR_(≥ 0) : r ≤ 1 - V(x)/d}$ into
$
Gamma_0 &= {(x, r) in ∂ Omega_d : x_1 = 0}, \
Gamma_1 &= {(x, r) in ∂ Omega_d : abs(x_1) = 2 pi "or" abs(x_2) = 1 "or" r = 0}, \
Gamma_2 &= {(x, r) in ∂ Omega_d : r = 1 - V(x)/d}.
$
Here $Gamma_0$ is the symmetry plane, on which $phi.alt_1$ vanishes because it is odd in $x_1$ (@lem:parity); $Gamma_1$ collects the Neumann walls on which the boundary condition is satisfied by design; and $Gamma_2$ is the curved wall of the Barrel, on which the Neumann condition is only satisfied approximately.

We give two derivations from this residual to a pointwise bound. In @sec:pointwise-limit we treat the limit $d = oo$, where the problem reduces to the operator $L = -∆ + nabla V dot nabla$ on $Q$ and the ultracontractivity estimates of @sec:ultracontractivity make the bound fully explicit. In the finite-dimensional case, we instead follow @moler_bounds_1968 and add a harmonic correction that restores the boundary condition exactly, then control the correction by a barrier.

== Pointwise bounds in the limit $d = oo$ <sec:pointwise-limit>

At $d = oo$ the barrel eigenvalue problem reduces to the operator $L = -∆ + nabla V dot nabla$ on the base $Q$, self-adjoint on $L^2(mu)$ with $dif mu = Z^(-1) e^(-V) dif x$. We use its Neumann eigenpairs $0 = lambda_0 < lambda_1 ≤ lambda_2 ≤ ...$, with $L^2(mu)$-orthonormal eigenfunctions $phi.alt_0 ≡ 1, phi.alt_1, phi.alt_2, ...$, and the enclosures $underline(lambda_1) ≤ lambda_1 ≤ overline(lambda_1)$ and $underline(lambda_2) ≤ lambda_2 ≤ overline(lambda_2)$ of @sec:eigenvalues. We normalize the approximation by $norm(phi.alt_*)_(L^2(mu)) = 1$ and compute its residual $(L - lambda_*) phi.alt_*$, in both $L^oo$ and $L^2(mu)$.

Let $(P_t)_(t ≥ 0)$ be the semigroup generated by $-L$, so that $∂_t P_t = -L P_t$ and $P_t phi.alt_k = e^(-lambda_k t) phi.alt_k$. Set $Q_t := e^(lambda_1 t) P_t$, so that the principal eigenfunction is a fixed point, $Q_t phi.alt_1 = phi.alt_1$, while $Q_t phi.alt_* -> inner(phi.alt_1, phi.alt_*) phi.alt_1$ as $t -> oo$. The ultracontractivity estimate of @thm:ultracontractivity gives a constant $C_t$ -- computed at $d = oo$ in @sec:ultracontractivity -- with
$
norm(P_t f)_oo ≤ C_t norm(f)_(L^2(mu)), "for all" t > 0.
$

#theorem[
  Let $phi.alt_1$ be the principal eigenfunction of $L = -∆ + nabla V dot nabla$ on $Q$, and let $phi.alt_*$, normalized by $norm(phi.alt_*)_(L^2(mu)) = 1$, be the approximation produced by the method of particular solutions with approximate eigenvalue $lambda_*$. With the eigenvalue enclosures $underline(lambda_1) ≤ lambda_1 ≤ overline(lambda_1)$ and $underline(lambda_2) ≤ lambda_2 ≤ overline(lambda_2)$ of @sec:eigenvalues,
  $
  norm(phi.alt_* - phi.alt_1)_oo
  ≤& min_(s_1 ≥ 0) [ (norm((L - lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo) (e^(s_1 overline(lambda_1)) - 1) / underline(lambda_1) \
  &+ (norm((L - lambda_*) phi.alt_*)_(L^2(mu)) + abs(lambda_* - lambda_1)) integral_(s_1)^oo C_(s slash 2) e^(-(underline(lambda_2) slash 2 - overline(lambda_1)) s) dif s ],
  $
  where $abs(lambda_* - lambda_1) ≤ max(lambda_* - underline(lambda_1), overline(lambda_1) - lambda_*)$.
]<thm:pointwise-limit>
#proof[
  Because $Q_t phi.alt_1 = phi.alt_1$ and $Q_t phi.alt_* -> phi.alt_1$ as $t -> oo$ (using that $phi.alt_*$ is $L^2(mu)$-normalized and approximates $phi.alt_1$, so $inner(phi.alt_1, phi.alt_*) -> 1$), and since $∂_s Q_s = -(L - lambda_1) Q_s$, we write the error as a time integral,
  $
  phi.alt_1 - phi.alt_* = lim_(t -> oo) (Q_t phi.alt_* - phi.alt_*) = - integral_0^oo Q_s (L - lambda_1) phi.alt_* dif s,
  $

  and therefore

  $
  norm(phi.alt_* - phi.alt_1)_oo ≤ integral_0^oo norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s.
  $<eq:my-favorite-integral>

  The function $(L - lambda_1) phi.alt_*$ is $L^2(mu)$-orthogonal to both $phi.alt_0 ≡ 1$ and $phi.alt_1$. Indeed, orthogonality to $phi.alt_0$ follows immediately from $(L - lambda_1) phi.alt_* = (L - lambda_*) phi.alt_* + (lambda_* - lambda_1) phi.alt_*$ and the fact that $phi.alt_*$ is antisymmetric in $x_1$ while $mu$ is symmetric. Orthogonality to the principal eigenfunction is by self-adjointness, $inner(phi.alt_1, (L - lambda_1) phi.alt_*) = inner((L - lambda_1) phi.alt_1, phi.alt_*) = 0$. Hence $P_s$ lets $(L - lambda_1) phi.alt_*$ decay at the rate $e^(-lambda_2)$ instead of only $e^(-lambda_1)$, and therefore,

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  = e^(lambda_1 s) norm(P_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  ≤ e^(-(lambda_2 - lambda_1) s) norm((L - lambda_1) phi.alt_*)_(L^2(mu)).
  $

  If we leave ourselves some slack and apply $Q_s$ only for time $s slash 2$, then

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  ≤ e^(-(lambda_2 - lambda_1) s slash 2) norm(Q_(s slash 2)(L - lambda_1) phi.alt_*)_(L^2(mu)),
  $

  and we can use the remaining smoothing time $s slash 2$ to pass to $L^oo$. Applying the ultracontractivity estimate of @thm:ultracontractivity,

  $
  norm(Q_(s) (L - lambda_1) phi.alt_*)_oo
  ≤ C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) norm((L - lambda_1) phi.alt_*)_(L^2(mu)).
  $<eq:splitting-trick>

  Since $C_(s slash 2)$ blows up as $s -> 0$, this bound is only useful for times above some threshold $s_1$, which is a free parameter. Below it we resort to the maximum-principle estimate $norm(P_t g)_oo ≤ norm(g)_oo$, that is 

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_oo
  ≤ e^(lambda_1 s) norm((L - lambda_1) phi.alt_*)_oo.
  $

  We now split the integral in @eq:my-favorite-integral at $s_1$ and write $(L - lambda_1) phi.alt_* = (L - lambda_*) phi.alt_* + (lambda_* - lambda_1) phi.alt_*$. Using $norm(phi.alt_*)_(L^2(mu)) = 1$, and the two derived bounds for the intgral

  $
  integral_0^(s_1) norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s ≤ (norm((L - lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo) integral_0^(s_1) e^(lambda_1 s) dif s,
  $

  and

  $
  integral_(s_1)^oo norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s ≤ (norm((L - lambda_*) phi.alt_*)_(L^2(mu)) + abs(lambda_* - lambda_1)) integral_(s_1)^oo C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) dif s.
  $

  Adding the two contributions, evaluating $integral_0^(t) e^(lambda s) dif s = (e^(lambda t) - 1) slash lambda$, and inserting the eigenvalue enclosures ($lambda_1 ≤ overline(lambda_1)$ in the numerator and $lambda_1 ≥ underline(lambda_1)$ in the denominator of the head, and $lambda_2 slash 2 - lambda_1 ≥ underline(lambda_2) slash 2 - overline(lambda_1)$ in the tail) gives the stated bound after minimizing over $s_1 ≥ 0$.
]

#remark[
  The even time split $s = s slash 2 + s slash 2$ leading to @eq:splitting-trick is arbitrary. Splitting instead as $s = alpha s + (1 - alpha) s$, with smoothing time $alpha s$ and decay time $(1 - alpha) s$, replaces the integrand factor by
  $
  C_(alpha s) e^(lambda_1 alpha s - (lambda_2 - lambda_1) (1 - alpha) s),
  $
  which can be optimized over $alpha in (0, 1)$.
]


/*
Now, since $Q_t phi.alt_1 = phi.alt_1$ and by the triangle inequality, we have

$
norm(phi.alt_* - phi.alt_1)_oo 
&≤ norm(Q_t phi.alt_* - phi.alt_*)_oo + norm(Q_t phi.alt_* - phi.alt_1)_oo \
&≤ e^(lambda_1 t)(t epsilon + t abs(lambda_* - lambda_1) norm(phi.alt_*)_oo + C_t norm(phi.alt_* - phi.alt_1)_2),
$

where we used the Wang-Li-Yau inequality. We reduced the problem to showing that $phi.alt$ is close to $phi.alt_1$ in $L^2$.



observe that $∂_t Q_t = lambda_1 e^t P_t - L e^t P_t = -(L-lambda_1)Q_t$. Therefore, 

$
norm(∂_t Q_t phi.alt_*)_oo 
&= norm(Q_t (L-lambda_1) phi.alt_*)_oo \
&≤ e^(lambda_1 t) norm((L-lambda_1)phi.alt_*)_oo \
&≤ e^(lambda_1 t) (norm((L-lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo) \
&≤ e^(lambda_1 t) (epsilon + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo)
$ <eq:partialQphi.alt-bound>

by the maximum principle. It follows that

$
norm(Q_t phi.alt_* - phi.alt_*)_oo 
≤ norm(Q_0 phi.alt_* - phi.alt_*)_oo +  t norm(∂_t (Q_t phi.alt_* - phi.alt_*))_oo
= t norm(∂_t Q_t phi.alt_*)_oo
≤ t e^(lambda_1 t) (epsilon + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo)
$

*Can we get rid of the $e^(lambda_1 t)$ factor?* #margin-note-a[Can you please check this?] In the step $norm(Q_t (L-lambda_1) phi.alt_*)_oo ≤ e^(lambda_1 t) norm((L-lambda_1)phi.alt_*)_oo$ in @eq:partialQphi.alt-bound we only used the maximum principle, which is probably too pessimistic. Remember that $Q_t phi.alt_1 = phi.alt_1$. Since $phi.alt_*$ is a good approximation of $phi.alt_1$, we expect $Q_t phi.alt_* approx phi.alt_*$ and thus $norm(Q_t (L-lambda_1) phi.alt_*)_oo approx epsilon + abs(lambda_* - lambda_1)norm(phi.alt_*)_oo$. Let us write $phi.alt_* = sum_j c_j phi.alt_j$ with $c_j = inner(phi.alt_j, phi.alt_*)$, assume $norm(phi.alt_*)_(L^2(e^(-V))) = 1$ then $sum c_j^2 = 1$ and $c_1 ≤ 1$. Now,

$
Q_t (L-lambda_1) 
=  sum_(j≥2) e^((lambda_1-lambda_j)t) (lambda_j - lambda_1) c_j phi.alt_j.
$

By Cauchy-Schwarz we have

$
abs(sum_(j≥2) e^((lambda_1-lambda_j)t) (lambda_j - lambda_1) c_j phi.alt_j)^2
&≤ (sum_(j≥2) (lambda_j - lambda_1)^2 c_j^2) (sum_(j≥2) e^(2(lambda_1-lambda_j)t) phi.alt_j^2) \
&≤ norm((L-lambda_1) phi.alt_*)_(L^2(e^(-V)))^2 (e^(2 lambda_1 t) p_(2t) (x,x) - phi.alt_1(x)^2),
$
where $p_t (x,y) = sum_j e^(-lambda_j t) phi.alt_j (x) phi.alt_j (y)$ is the heat kernel. So

$
norm(Q_t (L-lambda_1) phi.alt_*)_oo
≤ norm((L-lambda_1) phi.alt_*)_(L^2(e^(-V))) sup_x sqrt(e^(2 lambda_1 t) p_(2t) (x,x) - phi.alt_1(x)^2).
$

Now we need a bound of $norm((L-lambda_1) phi.alt_*)_(L^2(e^(-V)))$ instead of $norm((L-lambda_1) phi.alt_*)_oo$, which is much better since the point where the residual is worst is in the wing where $e^(-V)$ is very small. 

Lets try a nicer version of the same argument. Let $f in {phi.alt_1}^perp$, then

$
norm(Q_t f)_2
= e^(lambda_1 t) norm(P_t f)_2
≤ e^(lambda_1 t) e^(-lambda_2 t) norm(f)_2
≤ e^(-(lambda_2-lambda_1) t) norm(f)_2.
$

Now, we have $norm(Q_(s + t) f)_(oo) ≤ C_s norm(Q_t f)_2 ≤ C_s e^(-(lambda_2-lambda_1)t) norm(f)_2$. Since $(L-lambda_1) phi.alt_*$ is orthogonal to $phi.alt_1$, it follows immediately that

$
norm(Q_t (L-lambda_1) phi.alt_*)_oo 
&≤ C_(t\/2) e^(-2(lambda_2-lambda_1)t) norm((L-lambda_1) phi.alt_*)_(L^2(e^(-V))). // \
// &≤ C_(t\/2) e^(-(lambda_2-lambda_1)t) (norm((L-lambda_*) phi.alt_*)_(L^2(e^(-V))) + abs(lambda_*-lambda_1))

$
*/

== Barriers for the finite dimensional case

Suppose $phi.alt_*$ is an approximation of $phi.alt_1$ in the sense that

$
-∆ phi.alt_* &= lambda_* phi.alt_* \
phi.alt_* &= 0 "on" Gamma_0 \
∂_arrow(n) phi.alt_* &= 0 "on" Gamma_1 \
norm(∂_arrow(n) phi.alt_*)_oo &≤ epsilon "on" Gamma_2.
$

We cannot find barriers for $phi.alt$ directly, instead we bound the correction (see Moler-Payne) needed for $phi.alt_*$ satisfy the boundary condition. However then the corrected approximate eigenfunction is not a perfect eigenfunction in the interior any more. Moler-Payne show that this corrected eigenfunction is close to the true eigenfunction in the $L^2$ sense. We then upgrade this $L^2$ estimate to an $L^oo$ estimate using the Wang-Li-Yau inequality.

Let $w$ be the correction we have to add to $phi.alt_*$ to satisfy the Neumann boundary condition, i.e.

$
-∆w &= 0 \
w &= 0 "on" Gamma_0 \
∂_arrow(n) w(x,r) &= -∂_arrow(n) phi.alt_*(x,r) "on" Gamma_1 union Gamma_2.
$

Now $phi.alt_* + w$ satisfies the boundary conditions exactly at the cost $-∆(phi.alt_* + w) = lambda phi.alt_* ≠ lambda_* (phi.alt_* + w)$. According to Moler-Payne it follows that 

#lemma[@moler_bounds_1968][
  $
  norm(phi.alt_*-phi.alt_1)_2 ≤ norm(w)_2/alpha (1 + norm(w)_2^2/alpha^2)^(1/2),
  $

  where $alpha= abs(lambda_2 - lambda_*)\/lambda_2 = 1 - lambda_* / lambda_2 ≤ 1 - lambda_* / overline(lambda_2)$. 

  $
  abs(lambda_* - lambda_1) ≤ (sqrt(2) norm(w) + norm(w)^2)/(1-norm(w)) lambda_* \
  lambda_1 ≤ lambda_* / (1-norm(w)_2)
  $
]

#inline-note-a[
  Maybe the Rayleigh-quotient is a better upper bound of $lambda_1$:
  $
  lambda_1 ≤ integral abs(nabla phi.alt_*)^2
  &= -integral phi.alt_* ∆ phi.alt_* + integral phi.alt_* ∂_arrow(n) phi.alt_* \
  &= lambda_* + integral_Gamma_1 phi.alt_* ∂_arrow(n) phi.alt_*
  $
]

However, we want pointwise bounds and can now, since we transformed to and interior problem, use the same procedure as in the infinite dimensional case: $norm((-∆-lambda_*)(phi.alt_* + w))_oo = lambda_* norm(w)_oo$, by the same argument as before we conclude that 

#inline-note-a[
  Let's redo this.

  $
  norm(phi.alt_* + w - phi.alt_1)_oo \
  ≤ norm((-∆-lambda_1) (phi.alt_* + w))_oo ∫_0^s_1 e^(lambda_1 s) dif s + norm((-∆-lambda_1) (phi.alt_* + w))_2 ∫_(s_1)^oo C_(s\/2) e^(-2(lambda_2-lambda_1) s) dif s.
  $

  We have 
  
  $
  norm((-∆-lambda_1) (phi.alt_* + w)) 
  &≤ norm((-∆-lambda_1) phi.alt_*) + lambda_1 norm(w) \
  &≤ epsilon + abs(lambda_* - lambda) norm(phi.alt_*) + lambda_1 norm(w),
  $

  and $abs(lambda_* - lambda_1) ≤ (sqrt(2) norm(w) + norm(w)^2)/(1-norm(w)) lambda_*$. 

]

$
norm(phi.alt_* + w - phi.alt_1)_oo 
≤ e^(lambda_1 t)(lambda_* norm(w)_oo + abs(lambda_* - lambda_1) norm(phi.alt_* + w)_oo + C_t norm(phi.alt_* + w - phi.alt_1)_2) \
≤ e^(lambda_1 t)(lambda_* norm(w)_oo + abs(lambda_* - lambda_1) (norm(phi.alt_*)_oo + norm(w)_oo) + C_t (norm(phi.alt_* - phi.alt_1)_2 + norm(w)_2)) \
$







In order to bound $w$ we use a barrier estimate, let $v$ be such that

$
-∆v &≥ 0 \
v &= 0 "on" Gamma_0 \
∂_arrow(n) v &≥ 0 "on" Gamma_1 \
∂_arrow(n) v(x,r) &≥ abs(∂_arrow(n) phi.alt_*) "on" Gamma_2.
$

Let $f := w - v$, then

$
-∆ f &≤ 0 \
∂_arrow(n) f &≤ 0
$

Now,

$
norm(nabla f^+)_2^2 = ∫_Ω nabla f dot nabla f^+ = ∫_Ω (-∆ f) f^+ + ∫_(Gamma_1 + Gamma_2) (∂_arrow(n) f) f^+ ≤ 0,
$

showing $f^+$ is constant. Since $f^+$ vanishes on $Gamma_0$ it must be zero everywhere, we conclude that $w ≤ v$. The same argument with $-w$ inplace of $w$ gives $abs(w) ≤ v$.