#import "template.typ": *

= Pointwise bounds of the eigenfunction <sec:pointwise>

The method of particular solutions of @numerics returns an approximate eigenpair $(lambda_*, phi.alt_*)$ that satisfies the interior equation $-∆ phi.alt_* = lambda_* phi.alt_*$ exactly and has a small residual in the boundary condition. In this section we turn this boundary residual into a pointwise bound on the distance to the true principal eigenfunction $phi.alt_1$. We split the boundary of the reduced barrel $Omega_d = {(x, r) in Q times RR_(≥ 0) : r ≤ 1 - V(x)/d}$ into
$
Gamma_0 &= {(x, r) in ∂ Omega_d : x_1 = 0}, \
Gamma_1 &= {(x, r) in ∂ Omega_d : abs(x_1) = 2 pi "or" abs(x_2) = 1 "or" r = 0}, \
Gamma_2 &= {(x, r) in ∂ Omega_d : r = 1 - V(x)/d}.
$
Here $Gamma_0$ is the symmetry plane, on which $phi.alt_1$ vanishes because it is odd in $x_1$ (@lem:parity); $Gamma_1$ collects the Neumann walls on which the boundary condition is satisfied by design; and $Gamma_2$ is the curved wall of the Barrel, on which the Neumann condition is only satisfied approximately.

We give two derivations from this residual to a pointwise bound. In @sec:pointwise-limit we treat the limit $d = oo$, where the problem reduces to the operator $L = -∆ + nabla V dot nabla$ on $Q$ and the ultracontractivity estimates of @sec:ultracontractivity make the bound fully explicit. In the finite-dimensional case, we instead follow @moler_bounds_1968 and add a harmonic correction that restores the boundary condition exactly, then control the correction by a barrier.

== Pointwise bounds in the limit $d = oo$ <sec:pointwise-limit>

At $d = oo$ the barrel eigenvalue problem reduces to the operator $L = -∆ + nabla V dot nabla$ on the base $Q$, self-adjoint on $L^2(mu)$ with $dif mu = Z^(-1) e^(-V) dif x$. We use its Neumann eigenpairs $0 = lambda_0 < lambda_1 ≤ lambda_2 ≤ ...$, with $L^2(mu)$-orthonormal eigenfunctions $phi.alt_0 ≡ 1, phi.alt_1, phi.alt_2, ...$, and the enclosures $underline(lambda_1) ≤ lambda_1 ≤ overline(lambda_1)$ and $underline(lambda_2) ≤ lambda_2 ≤ overline(lambda_2)$ of @sec:eigenvalues. We normalize the approximation by $norm(phi.alt_*)_(L^2(mu)) = 1$ and compute its residual $(L - lambda_*) phi.alt_*$, in both $L^oo$ and $L^2(mu)$.

Let $(P_t)_(t ≥ 0)$ be the semigroup generated by $-L$, so that $∂_t P_t = -L P_t$ and $P_t phi.alt_k = e^(-lambda_k t) phi.alt_k$. Set $Q_t := e^(lambda_1 t) P_t$, so that the principal eigenfunction is a fixed point, $Q_t phi.alt_1 = phi.alt_1$, while $Q_t phi.alt_* -> inner(phi.alt_1, phi.alt_*) phi.alt_1$ as $t -> oo$. The ultracontractivity estimate of @thm:ultracontractivity gives a constant $C_t$ -- computed at $d = oo$ in @sec:ultracontractivity -- with
$
norm(P_t f)_oo ≤ C_t norm(f)_(L^2(mu)), "for all" t > 0.
$

#theorem[
  Let $phi.alt_1$ be the principal eigenfunction of $L = -∆ + nabla V dot nabla$ on $Q$, and let $phi.alt_*$, normalized by $norm(phi.alt_*)_(L^2(mu)) = 1$, be the approximation produced by the method of particular solutions with approximate eigenvalue $lambda_*$. With the eigenvalue enclosures $underline(lambda_1) ≤ lambda_1 ≤ overline(lambda_1)$ and $underline(lambda_2) ≤ lambda_2 ≤ overline(lambda_2)$ of @sec:eigenvalues,
  $
  norm(phi.alt_* - phi.alt_1)_oo
  ≤& min_(s_1 ≥ 0) [ (norm((L - lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo) (e^(s_1 overline(lambda_1)) - 1) / underline(lambda_1) \
  &+ (norm((L - lambda_*) phi.alt_*)_(L^2(mu)) + abs(lambda_* - lambda_1)) integral_(s_1)^oo C_(s slash 2) e^(-(underline(lambda_2) slash 2 - overline(lambda_1)) s) dif s ],
  $
  where $abs(lambda_* - lambda_1) ≤ max(lambda_* - underline(lambda_1), overline(lambda_1) - lambda_*)$.
]<thm:pointwise-limit>
#proof[
  Because $Q_t phi.alt_1 = phi.alt_1$ and $Q_t phi.alt_* -> phi.alt_1$ as $t -> oo$ (using that $phi.alt_*$ is $L^2(mu)$-normalized and approximates $phi.alt_1$, so $inner(phi.alt_1, phi.alt_*) -> 1$), and since $∂_s Q_s = -(L - lambda_1) Q_s$, we write the error as a time integral,
  $
  phi.alt_1 - phi.alt_* = lim_(t -> oo) (Q_t phi.alt_* - phi.alt_*) = - integral_0^oo Q_s (L - lambda_1) phi.alt_* dif s,
  $

  and therefore

  $
  norm(phi.alt_* - phi.alt_1)_oo ≤ integral_0^oo norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s.
  $<eq:my-favorite-integral>

  The function $(L - lambda_1) phi.alt_*$ is $L^2(mu)$-orthogonal to both $phi.alt_0 ≡ 1$ and $phi.alt_1$. Indeed, orthogonality to $phi.alt_0$ follows immediately from $(L - lambda_1) phi.alt_* = (L - lambda_*) phi.alt_* + (lambda_* - lambda_1) phi.alt_*$ and the fact that $phi.alt_*$ is antisymmetric in $x_1$ while $mu$ is symmetric. Orthogonality to the principal eigenfunction is by self-adjointness, $inner(phi.alt_1, (L - lambda_1) phi.alt_*) = inner((L - lambda_1) phi.alt_1, phi.alt_*) = 0$. Hence $P_s$ lets $(L - lambda_1) phi.alt_*$ decay at the rate $e^(-lambda_2)$ instead of only $e^(-lambda_1)$, and therefore,

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  = e^(lambda_1 s) norm(P_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  ≤ e^(-(lambda_2 - lambda_1) s) norm((L - lambda_1) phi.alt_*)_(L^2(mu)).
  $

  If we leave ourselves some slack and apply $Q_s$ only for time $s slash 2$, then

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_(L^2(mu))
  ≤ e^(-(lambda_2 - lambda_1) s slash 2) norm(Q_(s slash 2)(L - lambda_1) phi.alt_*)_(L^2(mu)),
  $

  and we can use the remaining smoothing time $s slash 2$ to pass to $L^oo$. Applying the ultracontractivity estimate of @thm:ultracontractivity,

  $
  norm(Q_(s) (L - lambda_1) phi.alt_*)_oo
  ≤ C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) norm((L - lambda_1) phi.alt_*)_(L^2(mu)).
  $<eq:splitting-trick>

  Since $C_(s slash 2)$ blows up as $s -> 0$, this bound is only useful for times above some threshold $s_1$, which is a free parameter. Below it we resort to the maximum-principle estimate $norm(P_t g)_oo ≤ norm(g)_oo$, that is 

  $
  norm(Q_s (L - lambda_1) phi.alt_*)_oo
  ≤ e^(lambda_1 s) norm((L - lambda_1) phi.alt_*)_oo.
  $

  We now split the integral in @eq:my-favorite-integral at $s_1$ and write $(L - lambda_1) phi.alt_* = (L - lambda_*) phi.alt_* + (lambda_* - lambda_1) phi.alt_*$. Using $norm(phi.alt_*)_(L^2(mu)) = 1$, and the two derived bounds for the intgral

  $
  integral_0^(s_1) norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s ≤ (norm((L - lambda_*) phi.alt_*)_oo + abs(lambda_* - lambda_1) norm(phi.alt_*)_oo) integral_0^(s_1) e^(lambda_1 s) dif s,
  $

  and

  $
  integral_(s_1)^oo norm(Q_s (L - lambda_1) phi.alt_*)_oo dif s ≤ (norm((L - lambda_*) phi.alt_*)_(L^2(mu)) + abs(lambda_* - lambda_1)) integral_(s_1)^oo C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) dif s.
  $

  Adding the two contributions, evaluating $integral_0^(t) e^(lambda s) dif s = (e^(lambda t) - 1) slash lambda$, and inserting the eigenvalue enclosures ($lambda_1 ≤ overline(lambda_1)$ in the numerator and $lambda_1 ≥ underline(lambda_1)$ in the denominator of the head, and $lambda_2 slash 2 - lambda_1 ≥ underline(lambda_2) slash 2 - overline(lambda_1)$ in the tail) gives the stated bound after minimizing over $s_1 ≥ 0$.
]

#remark[
  The even time split $s = s slash 2 + s slash 2$ leading to @eq:splitting-trick is arbitrary. Splitting instead as $s = alpha s + (1 - alpha) s$, with smoothing time $alpha s$ and decay time $(1 - alpha) s$, replaces the integrand factor by
  $
  C_(alpha s) e^(lambda_1 alpha s - (lambda_2 - lambda_1) (1 - alpha) s),
  $
  which can be optimized over $alpha in (0, 1)$.
]

== Pointwise bounds in the finite-dimensional case

In the limit $d = oo$ the eigenvalue problem is effectively an interior one: the mass of the barrel concentrates at the outer boundary, the approximation $phi.alt_*$ satisfies the Neumann condition on $∂Q$ by construction, and the only error left to control is the "interior" residual $(L - lambda_*) phi.alt_*$. In finite dimensions this is no longer the case. The approximation satisfies the interior equation $-∆ phi.alt_* = lambda_* phi.alt_*$ exactly, but it now leaves a residual in the Neumann condition on $Gamma_1 union Gamma_2$. Following @moler_bounds_1968, we first internalize this boundary residual, then the same proof as in @sec:pointwise-limit applies.

We correct the boundary condition with a harmonic function $w$ solving

$
-∆ w &= 0 "in" Omega_d, \
w &= 0 "on" Gamma_0, \
∂_arrow(n) w(x, r) &= -∂_arrow(n) phi.alt_*(x, r) "on" Gamma_1 union Gamma_2.
$<eq:harmonic-correction>
By construction $phi.alt_* + w$ satisfies the Neumann condition exactly, and since $w$ is harmonic, using $-∆ phi.alt_* = lambda_* phi.alt_*$ and $-∆ w = 0$, we have

$
(-∆ - lambda_1)(phi.alt_* + w) = (lambda_* - lambda_1) phi.alt_* - lambda_1 w.
$<eq:internalized-residual>

The corrected function $phi.alt_* + w$ thus takes over the role that $phi.alt_*$ played in the limit case. It remains to control the correction $w$, which we do with a barrier.

#lemma[
  Let $w$ solve @eq:harmonic-correction, and let $v$ be a supersolution satisfying
  $
  -∆ v &≥ 0 "in" Omega_d, \
  v &= 0 "on" Gamma_0, \
  ∂_arrow(n) v &≥ 0 "on" Gamma_1, \
  ∂_arrow(n) v(x, r) &≥ abs(∂_arrow(n) phi.alt_*(x, r)) "on" Gamma_2.
  $
  Then $abs(w) ≤ v$ on $Omega_d$, in particular $norm(w)_oo ≤ norm(v)_oo$ and $norm(w)_2 ≤ norm(v)_2$.
]<lem:barrier>
#proof[
  Set $f := w - v$. Then $-∆ f ≤ 0$ in $Omega_d$, with $∂_arrow(n) f ≤ 0$ on $Gamma_1 union Gamma_2$ and $f = 0$ on $Gamma_0$. Testing against the positive part $f^+$ and integrating by parts,
  $
  norm(nabla f^+)_2^2 = integral_(Omega_d) nabla f dot nabla f^+ = integral_(Omega_d) (-∆ f) f^+ + integral_(Gamma_1 union Gamma_2) (∂_arrow(n) f) f^+ ≤ 0,
  $
  so $f^+$ is constant. Since it vanishes on $Gamma_0$ it is identically zero, giving $w ≤ v$. Repeating the argument with $-w$ in place of $w$ yields $abs(w) ≤ v$.
]

#theorem[
  Let $phi.alt_1$ be the principal Neumann eigenfunction of $-∆$ on $Omega_d$, and let $phi.alt_*$, normalized by $norm(phi.alt_*)_2 = 1$ and satisfying $-∆ phi.alt_* = lambda_* phi.alt_*$ exactly in the interior, be the approximation produced by the method of particular solutions. Let $w$ be the harmonic correction @eq:harmonic-correction and $v$ a barrier as in @lem:barrier. With the eigenvalue enclosures $underline(lambda_1) ≤ lambda_1 ≤ overline(lambda_1)$ and $underline(lambda_2) ≤ lambda_2 ≤ overline(lambda_2)$ of @sec:eigenvalues,
  $
  norm(phi.alt_* - phi.alt_1)_oo
  ≤& norm(v)_oo + min_(s_1 ≥ 0) [ (abs(lambda_* - lambda_1) norm(phi.alt_*)_oo + overline(lambda_1) norm(v)_oo) (e^(s_1 overline(lambda_1)) - 1) / underline(lambda_1) \
  &+ (abs(lambda_* - lambda_1) + overline(lambda_1) norm(v)_2) integral_(s_1)^oo C_(s slash 2) e^(-(underline(lambda_2) slash 2 - overline(lambda_1)) s) dif s ],
  $
  where $abs(lambda_* - lambda_1) ≤ max(lambda_* - underline(lambda_1), overline(lambda_1) - lambda_*)$.
]<thm:pointwise-finite>
#proof[
  Because $phi.alt_* + w$ satisfies the Neumann condition exactly, the argument of @thm:pointwise-limit applies to $phi.alt_* + w$ in place of $phi.alt_*$ and $-∆$ in place of $L$. The only thing to verify is that $phi.alt_*$ is orthogonal to $phi.alt_0 ≡ 1$ and $phi.alt_1$. The approximate eigenfunction $phi.alt_*$ is odd in $x_1$ by designg and $w$ is odd by @eq:harmonic-correction. The exact Neumann condition makes the boundary terms in Green's identity vanish, so $inner(phi.alt_1, (-∆ - lambda_1)(phi.alt_* + w)) = inner((-∆ - lambda_1) phi.alt_1, phi.alt_* + w) = 0$. Write $P_s$ for the Neumann heat semigroup on $Omega_d$, $Q_s = e^(lambda_1 s) P_s$, and $C_t$ for the ultracontractivity constant of @thm:ultracontractivity. The same time split of @eq:my-favorite-integral at $s_1$, the maximum principle below $s_1$, and the $s slash 2$ ultracontractivity bound above $s_1$, gives

  $
  norm(phi.alt_* + w - phi.alt_1)_oo ≤& norm((-∆ - lambda_1)(phi.alt_* + w))_oo integral_0^(s_1) e^(lambda_1 s) dif s \
  &+ norm((-∆ - lambda_1)(phi.alt_* + w))_2 integral_(s_1)^oo C_(s slash 2) e^(-(lambda_2 slash 2 - lambda_1) s) dif s.
  $

  From @eq:internalized-residual and $norm(phi.alt_*)_2 = 1$ it follows that,

  $
  norm((-∆ - lambda_1)(phi.alt_* + w))_oo &≤ abs(lambda_* - lambda_1) norm(phi.alt_*)_oo + lambda_1 norm(w)_oo, \
  norm((-∆ - lambda_1)(phi.alt_* + w))_2 &≤ abs(lambda_* - lambda_1) + lambda_1 norm(w)_2.
  $

  Inserting the barrier bounds $norm(w)_oo ≤ norm(v)_oo$ and $norm(w)_2 ≤ norm(v)_2$ of @lem:barrier, the eigenvalue enclosures, and $integral_0^(s_1) e^(lambda_1 s) dif s ≤ (e^(s_1 overline(lambda_1)) - 1) slash underline(lambda_1)$, and using the triangle inequality $norm(phi.alt_* - phi.alt_1)_oo ≤ norm(phi.alt_* + w - phi.alt_1)_oo + norm(w)_oo$, gives the stated bound after minimizing over $s_1 ≥ 0$.
]



#inline-note-a[
  Maybe the Rayleigh-quotient should be computed like this:
  $
  lambda_1 ≤ integral abs(nabla phi.alt_*)^2
  &= -integral phi.alt_* ∆ phi.alt_* + integral phi.alt_* ∂_arrow(n) phi.alt_* \
  &= lambda_* + integral_Gamma_1 phi.alt_* ∂_arrow(n) phi.alt_*
  $
]